title: FIM docs
description: File Integrity Monitoring software documentation webpage
theme: just-the-docs
color_scheme: light

url: https://documentation.achiefs.github.io

aux_links:
  Source Repository: https://github.com/Achiefs/fim
