title: Achiefs documentation
description: File Integrity Monitoring software documentation webpage
theme: just-the-docs

url: https://documentation.achiefs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
